steps:
  - block: ":wave: Name Input"
    prompt: "Please provide your name"
    fields:
      - text: "Name"
        key: "user-name"

  - label: ":docker: Build Go Binary"
    key: "build"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
          workdir: /app
    command: |
      mkdir -p build
      go mod tidy
      go build -o build/hello hello/hello.go
      ls -l build
    artifact_paths:
      - "build/hello"

  - label: ":rocket: Execute Binary"
    depends_on:
      - "build"
    command: |
      buildkite-agent meta-data keys
      buildkite-agent artifact download "build/hello" .
      NAME=$(buildkite-agent meta-data get "user-name")
      chmod +x build/hello
      echo $NAME
      ./build/hello "$NAME"
